// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(in *jlexer.Lexer, out *AdList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(AdList, 0, 0)
			} else {
				*out = AdList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Ad
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(out *jwriter.Writer, in AdList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v AdList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel(l, v)
}
func easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(in *jlexer.Lexer, out *Ad) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "price":
			out.Price = float64(in.Float64())
		case "images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]string, 0, 4)
					} else {
						out.Images = []string{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Images = append(out.Images, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created":
			out.Created = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(out *jwriter.Writer, in Ad) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.Price != 0 {
		const prefix string = ",\"price\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.Price))
	}
	if len(in.Images) != 0 {
		const prefix string = ",\"images\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Images {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	if in.Created != "" {
		const prefix string = ",\"created\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Created))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Ad) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Ad) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson27d09f75EncodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Ad) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Ad) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson27d09f75DecodeGithubComKonstantinProninAdvertisingBackendInternalAdvertisementModel1(l, v)
}
